### ISSUE TITLE
AWS-Auth configmap is mis-configured

### ISSUE THREAD

**Issue by MarvinCai** [streamnative/terraform-aws-cloud#30]
Getting following error from EKS console:
`Your worker nodes do not have access to the cluster. Verify if the node instance role is present and correctly configured in the aws-auth ConfigMap.`
Node IAM Role ARN is
`arn:aws:iam::311022431024:role/StreamNative/sn-rxrevu-prod-us-east-120211109000743895600000009
`But in aws-auth configmap there is:
```
➜  /Users/marvincai  k get configmap aws-auth -nkube-system -oyaml
apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::311022431024:role/sn-rxrevu-prod-us-east-120211109000743895600000009"
      "username": "system:node:{{EC2PrivateDNSName}}"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::311022431024:role/aws-reserved/sso.amazonaws.com/us-west-2/AWSReservedSSO_AdministratorAccess_d24587bd48be062e"
      "username": "management-admin"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::311022431024:role/gcp_eks_admin"
      "username": "gcp"
  mapUsers: |
```
The 2 role ARNs doesn't match.
